# development params are automatically applied in hugo 'server' mode

# baseurls for stage and live sites are defined seperately
# this default for 'hugo server' doesn't seem to be modifiable here.
#baseURL = "http://localhost"

buildDrafts = true
buildFuture = true

