# development params are automatically applied in hugo 'server' mode

# baseurls for stage and live sites are defined seperately
baseurl = "http://localhost:3000"

buildDrafts = true
buildFuture = true

