version: '2'

#include: Taskvars.yml

tasks:

# Setup web-mc
  setup:
    cmds:
      - echo 'Starting'
      - task: hugo-installed
      - task: node-setup
      - task: node-setup-theme
      - echo 'Finished setup task'


  # Install node_modules
  node-setup:
    deps:
      - node-installed
    desc: Run npm install if node_modules doesn't exist
    cmds:
      - npm install
    status:
      - test -d node_modules

  # Install node_modules in theme
  node-setup-theme:
    deps:
      - node-setup
    dir: starters/five-page/themes/bunait
    desc: Symlink main node_modules in bunait theme and run npm install
    cmds:
      - ln -s ../../../../node_modules node_modules
      - npm install
    status:
      - test -d node_modules

  # Check if node installed
  node-installed:
    silent: true
    cmds:
      - |
        if ! command -v node > /dev/null; then
          echo "node is not installed. aborting."
          exit 1
        fi
      - echo "node installed, ok."

  hugo-installed:
    silent: true
    cmds:
      - |
        if ! command -v hugo > /dev/null; then
          echo "hugo is not installed. aborting."
          exit 1
        fi
      - echo "hugo installed, ok."


# Sites

# Copy starter to new site with new name
  new-site:
    cmds:
      - echo 'Creating new site' {{ .NAME }}
      - cp -rn starters/five-page sites/{{ .NAME }}
      - mv -n sites/{{ .NAME }}/themes/bunait sites/{{ .NAME }}/themes/{{ .NAME }}
      - find sites/{{ .NAME }}/ -not -path '*/\.git*' -type f -readable -exec sed -i "s/bunait/{{ .NAME }}/gI" {} \;
      - cd sites/{{ .NAME }} && git init
      - cd sites/{{ .NAME }} && git add .
      - cd sites/{{ .NAME }} && git commit -m"Initial Commit of HuMC generated site"
      - echo 'Finished creating site' {{ .NAME }}
      - echo 'A new git repo has been initialized in sites/{{ .NAME }} and all files committed.'
      - echo 'NOTE You need to add a git remote and push manually'
    silent: true
# Notes:
# For 'cp' and 'mv'
# -r is recursive
# -n will not overwrite existing
# -v is verbose
