version: '2'

tasks:

# Setup web-mc
  setup:
    cmds:
      - echo 'Starting'
      - hugo-installed
      - node-setup


  # Install node_modules
  node-setup:
    deps:
      - node_installed
    desc: Run npm install if node_modules doesn't exist
    cmds:
      - npm install
    status:
      - test -d node_modules

  # Check if node installed
  node_installed:
    silent: true
    cmds:
      - |
        if ! command -v node > /dev/null; then
          echo "node is not installed. aborting."
          exit 1
        fi
      - echo "node installed, ok."

  hugo-installed:
    silent: true
    cmds:
      - |
        if ! command -v hugo > /dev/null; then
          echo "hugo is not installed. aborting."
          exit 1
        fi
      - echo "hugo installed, ok."
