# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Pippy"
license = "MIT"
licenselink = "https://github.com/adrinux/Pippy/blob/master/LICENSE"
description = "A Hugo theme based on HTML5boilerplate and using hugo pipes"
homepage = "https://github.com/adrinux/Pippy"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Adrian Simmons"
  homepage = "https://perlucida.com"


