# Option used in all environments

languageCode = "en-us"
title = "My New Hugo Site"
description = "A web site built with Hugo"

theme = "bunait"

#disableKinds = ['RSS']
#summarylength = 36
#paginate = 10
#rssLimit = 6

#[permalinks]
#  blog = "/blog/:year/:month/:title/"

[imaging]
# For filter options see https://github.com/disintegration/imaging
resampleFilter = "Lanczos"
quality = "86"
anchor = "smart"
