[[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 500
  url = "/"

[[menu.main]]
  name = "Blog"
  identifier = "blog"
  weight = 900
  url = "/blog/"

[[menu.main]]
  name = "Style Guide"
  identifier = "styleguide"
  weight = 10000
  url = "/styleguide/"
