# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Bunait"
description = "A Hugo theme based on HTML5boilerplate and using hugo pipes."
tags = []
features = []
min_version = "0.54"

[author]
  name = "Adrian Simmons"
  homepage = "https://perlucida.com"


