# Option used in all environments

languageCode = "en-GB"
title = "Bunait"
description = "A web site built with Hugo & HuMC"

theme = "bunait"

#summarylength = 36
#paginate = 10
#disableKinds = ['RSS']
#rssLimit = 6

# Syntax highlighting with Chroma
# https://gohugo.io/content-management/syntax-highlighting/
# https://github.com/alecthomas/chroma
# Dont forget to generate stylesheet on cli
# hugo gen chromastyles --style=tango > themes/bunait/assets/css/chroma.css
pygmentsUseClasses = true
pygmentsStyle = "tango"
pygmentsCodefences = true

[permalinks]
blog = "/blog/:year-:month/:title/"

[imaging]
# For filter options see https://github.com/disintegration/imaging
resampleFilter = "Lanczos"
quality = 86
anchor = "smart"

# Personal/Organizational Params
[params.social]
# github = "username"
# linkedin = "username"
# twitter = "username"
